name: ${PROJECT_NAME:-backlog-mcp}
services:
  backlog-mcp-api:
    # container_nameを削除して、Docker Composeがプロジェクト名に基づいて自動的に名前を生成するようにする
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ..:/app
    environment:
      - BACKLOG_API_KEY=${BACKLOG_API_KEY}
      - BACKLOG_SPACE=${BACKLOG_SPACE}
      - BACKLOG_PROJECT=${BACKLOG_PROJECT}
      - BACKLOG_DISABLE_SSL_VERIFY=${BACKLOG_DISABLE_SSL_VERIFY:-false}
      - PORT=${PORT:-8000}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
