name: Python Tests & API Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: コード品質チェック
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pythonのセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Poetryのインストール
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Poetryの設定
      run: |
        poetry config virtualenvs.in-project true
    
    - name: Poetry依存関係のキャッシュ
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: 依存関係のインストール
      run: |
        pip install uv
        uv pip install --system poetry
        # pybacklogpyモジュールをローカルのwhlファイルからインストール
        pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
        # poetry.lockファイルを更新
        poetry lock
        poetry install --no-interaction
        # pybacklogpyモジュールのインストール確認
        poetry run pip list | grep pybacklogpy || echo "pybacklogpy not installed"
        # 仮想環境内にもpybacklogpyをインストール
        poetry run pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
    
    - name: コードスタイルチェック
      run: |
        poetry run python -m black app tests
        poetry run python -m isort app tests
        echo "コードスタイルを自動修正しました"
    
    - name: 型チェックの実行
      run: |
        # 型チェックのためのスタブファイルを作成
        mkdir -p .venv/lib/python3.10/site-packages/pybacklogpy
        touch .venv/lib/python3.10/site-packages/pybacklogpy/py.typed
        # 型チェックの実行
        poetry run python -m mypy --config-file mypy.ini app tests
    
    - name: セキュリティチェック
      run: |
        poetry run pip install bandit safety
        poetry run python -m bandit -r app -x tests
        poetry run python -m safety scan
        
  unit-tests:
    name: 単体テスト
    runs-on: ubuntu-latest
    needs: code-quality
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pythonのセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Poetryのインストール
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Poetryの設定
      run: |
        poetry config virtualenvs.in-project true
    
    - name: Poetry依存関係のキャッシュ
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: 依存関係のインストール
      run: |
        pip install uv
        uv pip install --system poetry
        # pybacklogpyモジュールをローカルのwhlファイルからインストール
        pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
        # poetry.lockファイルを更新
        poetry lock
        poetry install --no-interaction
        # pybacklogpyモジュールのインストール確認
        poetry run pip list | grep pybacklogpy || echo "pybacklogpy not installed"
        # 仮想環境内にもpybacklogpyをインストール
        poetry run pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
    
    - name: 単体テストの実行
      run: |
        poetry run python -m pytest tests/unit/ --cov=app --cov-report=xml --cov-report=html --cov-report=term
    
    - name: カバレッジ閾値チェック
      run: |
        poetry run pip install coverage-threshold
        poetry run coverage-threshold --line-coverage-min=80
    
    - name: カバレッジレポートのアップロード
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  integration-tests:
    name: 結合テスト & OpenAPI生成
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pythonのセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Poetryのインストール
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Poetryの設定
      run: |
        poetry config virtualenvs.in-project true
    
    - name: Poetry依存関係のキャッシュ
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: 依存関係のインストール
      run: |
        pip install uv
        uv pip install --system poetry
        # pybacklogpyモジュールをローカルのwhlファイルからインストール
        pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
        # poetry.lockファイルを更新
        poetry lock
        poetry install --no-interaction
        # pybacklogpyモジュールのインストール確認
        poetry run pip list | grep pybacklogpy || echo "pybacklogpy not installed"
        # 仮想環境内にもpybacklogpyをインストール
        poetry run pip install ./reference/pybacklogpy-0.12.1-py3-none-any.whl
    
    - name: 結合テストの実行
      run: |
        poetry run python -m pytest tests/integration/ --cov=app --cov-report=xml --cov-report=html --cov-report=term
    
    - name: カバレッジ閾値チェック
      run: |
        poetry run pip install coverage-threshold
        poetry run coverage-threshold --line-coverage-min=80
    
    - name: カバレッジレポートのアップロード
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
    
    - name: HTMLカバレッジレポートのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-integration
        path: htmlcov/
        retention-days: 7
        
    - name: アプリケーションの起動
      run: |
        poetry run python -m app.main &
        echo "アプリケーションを起動しました。5秒待機します..."
        sleep 5
        
    - name: OpenAPI仕様書の生成
      run: |
        poetry run python scripts/generate_openapi.py docs openapi.yaml
        
    - name: OpenAPI仕様書のアップロード
      uses: actions/upload-artifact@v4
      with:
        name: openapi-spec
        path: docs/openapi.yaml
        retention-days: 30

  cdk-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install CDK dependencies
        working-directory: cdk
        run: npm ci

      - name: Run CDK unit tests
        working-directory: cdk
        run: bash scripts/run-tests.sh
